### ISSUE TITLE
Add Calabash behavioral tests for sample apps

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#362]
The unit tests are not currently catching some behavioral issues, as we're discovering in testing the couchbase/couchbase-lite-net/issue-348 branch. We can use the sample apps for this purpose, especially with multiple tests on multiple devices running concurrently. To do that, we need to script them via something that can run from inside NUnit, and Calabash is a perfect fit.

**Comment by sethrosetter** [comment]
Closeout criteria

- [ ] 3 representative tests against SimpleAndroidSync.
    - [ ] device online / offline
    - [ ] add some data to client and verify push
    - [ ] add some data to sg and verify pull
- [ ] Document the process
