### ISSUE TITLE
ForestDB Storage Engine

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#391]

**Comment by borrrden** [comment]
- [X] P/Invoke "raw" layer
- [X] "ugly" fully marshalled C# layer
- [ ] Couchbase specific logic ("CBForest")
