### ISSUE TITLE
Add official openDatabase API for encryption/storage options

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-net#524]
Here's the [API draft doc](https://github.com/couchbaselabs/couchbase-lite-api/wiki/Open-Database-Options).

See also couchbase/couchbase-lite-ios#970

**Comment by borrrden** [comment]
- [X] Logic for 1.1 -> current SQLite
- [X] Logic for 1.1 -> current ForestDB
- [ ] Logic for current SQLite -> current ForestDB
- [ ] Logic for current ForestDB -> current SQLite
- [ ] Actual API change
