### ISSUE TITLE
Logging overhaul

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#576]

**Comment by borrrden** [comment]
A good chunk of this is done.  All that is left is to migrate the rest of the legacy log statements to use domains.  After that it's just a matter of sorting out some fine details.  I've updated the [wiki page](https://github.com/couchbase/couchbase-lite-net/wiki/Tracing--&-Logging) about logging but it is still subject to change until release.

**Comment by jamiltz** [comment]
Will it be possible to enable the different log levels in release builds as well? For example, to enable logging when using the build published on nugget.

**Comment by borrrden** [comment]
Yes that is one of the points of this. All levels will be available in release builds aside from the debug level.

**Comment by jamiltz** [comment]
Great!

**Comment by borrrden** [comment]
- [X] Add domain functionality
- [X] Add log scrubbing functionality (redacting insecure log items like user created content, usernames, emails, passwords, etc)
- [X] Add in logging verbosity levels to decouple from the trace listener verbosity levels
- [X] Add in a system for configuring the logger (and potentially other functions) via an external file
- [ ] Switch over all logging statements to the new style of logging
