### ISSUE TITLE
Optimize build pipeline

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-net#626]
Everything needs to work from a freshly cloned repo without ever opening the IDE:

- [X] Couchbase.Lite.Net45.sln
- [X] Couchbase.Lite.Net35.sln
- [X] Couchbase.Lite.iOS.sln
- [X] Couchbase.Lite.Android.sln
- [X] Couchbase.Lite.Net45.VS2015.sln
- [X] Couchbase.Lite.Net35.VS2015.sln
- [X] Couchbase.Lite.iOS.VS2015.sln
- [X] Couchbase.Lite.Android.VS2015.sln

**Comment by borrrden** [comment]
Note helps Issue #585

**Comment by elevine** [comment]
@borrrden I've been working on something similar for our fork.  With [Paket](https://fsprojects.github.io/Paket/) and [FAKE](http://fsharp.github.io/FAKE/), I've been able to automate the setup, build, packaging. and publishing steps.  

You can see the changes at this PR: https://github.com/APXLabs/couchbase-lite-net/pull/4.  Its somewhat based on the pattern from [Scripts To Rule Them All](https://github.com/github/scripts-to-rule-them-all).  What I've done so far is Windows specific, but it can easily be made cross platform.  

Hopefully you'll find this useful for this issue.  I'm happy to answer any questions if you have them.

**Comment by borrrden** [comment]
@elevine Oh nice!  I'm actually moving the other way and putting more of the work into the actual csproj file (as our product manager put it, it's basically ANT for .NET) but if I see anything nice I'll definitely use it.  A word of warning though:

The CBForest API hasn't been too stable and the prebuilt version for 1.2 is **not** compatible with the current master branch.

**Comment by elevine** [comment]
Thanks for the heads up about CBForest @borrrden!  We forked off from the last stable release (1.2.0.3).  What is the right version of cbforexst to use for that?

As far as FAKE goes, its more similar to [Gradle](http://gradle.org/whygradle-build-automation/) for Java.  We've recently transitioned over to FAKE, feeling that it was easier to create and maintain instead of trying to have our csproj files and MSBuild do everything.  FAKE still works with csproj and MSBuild though, as it has helpers to run those as well as a bunch of other things like NuGet and Xamarin. The full list is [here](http://fsharp.github.io/FAKE/apidocs/).

**Comment by borrrden** [comment]
If you stick with the fork you will be OK.  The problem will arise if you build CBForest master and use the prebuilt native binaries for 1.2.  They will be subtle errors too that you wouldn't suspect from this sort of thing (null reference exceptions, garbage output, etc).

**Comment by borrrden** [comment]
Oh, and I did look at a similar project (CAKE) for build automation as well, but so far I haven't done anything that I feel compels me to switch and then ask our build engineer to use.

**Comment by elevine** [comment]
Thank you @borrrden.  I know we looked into CAKE too and it seemed like another good option.  I think we chose FAKE due to some additional helpers it had.  In any case, it makes sense to choose what works best for your needs.
